import { createClient } from '@/lib/supabase/server';
import type { Benefit, Category, Product, ProductVariant } from '@/types/catalog';
import { hasSupabaseEnv } from '@/lib/supabase/env';

const configured = hasSupabaseEnv;
const categories: Category[] = [{ id:'mantas',name:'Mantas e Peseiras',slug:'mantas-e-peseiras',description:'Conforto e elegância para todos os ambientes.',image_url:'https://images.unsplash.com/photo-1583845112203-454c57d86011?auto=format&fit=crop&w=900&q=85',display_order:1,active:true },{id:'almofadas',name:'Almofadas',slug:'almofadas',description:'Texturas que abraçam e transformam seu espaço.',image_url:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=900&q=85',display_order:2,active:true}];
const products: Product[] = [{id:'coberta-la-natural',category_id:'mantas',name:'Coberta Lã Natural',slug:'coberta-la-natural',description:'Coberta em tons naturais que combina com qualquer ambiente. Conforto e elegância para todos os ambientes da casa.',price:229,image_url:'https://images.unsplash.com/photo-1583845112203-454c57d86011?auto=format&fit=crop&w=1000&q=85',origin:'100% fio têxtil natural, feito à mão',dimensions:'Sob encomenda',care:'Lavar à mão em água fria. Secar à sombra.',whatsapp_url:null,display_order:1,active:true,categories:{name:'Mantas e Peseiras',slug:'mantas-e-peseiras'}},{id:'manta-trico-creme',category_id:'mantas',name:'Manta Tricô Creme',slug:'manta-trico-creme',description:'Manta de tricô em fio creme, macia e aconchegante.',price:189,image_url:'https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=1000&q=85',origin:'100% fio têxtil natural, tricô artesanal manual',dimensions:'130 x 170 cm',care:'Lavar à mão em água fria. Secar à sombra na horizontal.',whatsapp_url:null,display_order:2,active:true,categories:{name:'Mantas e Peseiras',slug:'mantas-e-peseiras'}}];

export async function getSettings() { if (!configured) return { brand:{name:'Teia & Aconchego',tagline:'ARTE EM CADA DETALHE',footer:'Teia & Aconchego – Arte em cada detalhe'}, hero:{title:'Feito à mão. Pensado para acolher.',description:'Peças artesanais que levam beleza, aconchego e personalidade para o seu lar.',buttonText:'CONHEÇA O CATÁLOGO',imageUrl:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85'},contact:{whatsappUrl:'https://wa.me/5547999999999',phone:'(47) 99999-9999'} }; const supabase = await createClient(); const { data } = await supabase.from('site_settings').select('key,value'); return Object.fromEntries((data ?? []).map((row) => [row.key, row.value])); }
export async function getCategories(): Promise<Category[]> { if (!configured) return categories; const supabase = await createClient(); const { data } = await supabase.from('categories').select('*').eq('active', true).order('display_order'); return (data ?? []) as Category[]; }
export async function getBenefits(): Promise<Benefit[]> { if (!configured) return [{id:'1',icon:'♡',title:'Produção artesanal',description:'Feito à mão com amor e dedicação',display_order:1,active:true},{id:'2',icon:'◌',title:'Materiais premium',description:'Selecionamos os melhores materiais para você',display_order:2,active:true}]; const supabase = await createClient(); const { data } = await supabase.from('benefits').select('*').eq('active', true).order('display_order'); return (data ?? []) as Benefit[]; }
type PriceLabels = Record<string, string>;
const addPriceLabels = (items: Product[], labels: PriceLabels) => items.map((item) => ({ ...item, price_label: labels[item.id] ?? null }));
async function getPriceLabels() { const supabase = await createClient(); const { data } = await supabase.from('site_settings').select('value').eq('key', 'product_price_labels').maybeSingle(); return (data?.value ?? {}) as PriceLabels; }
async function getVariantsForProducts(productIds: string[]) { if (!productIds.length) return new Map<string, ProductVariant[]>(); const supabase = await createClient(); const { data } = await supabase.from('product_variants').select('*').in('product_id', productIds).eq('active', true).order('is_default', { ascending: false }).order('display_order'); return (data ?? []).reduce((grouped, variant) => { const item = variant as ProductVariant; grouped.set(item.product_id, [...(grouped.get(item.product_id) ?? []), item]); return grouped; }, new Map<string, ProductVariant[]>()); }
const addVariants = (items: Product[], variants: Map<string, ProductVariant[]>) => items.map((item) => ({ ...item, variants: variants.get(item.id) ?? [] }));
export async function getProducts(categorySlug?: string): Promise<Product[]> { if (!configured) return categorySlug ? products.filter((p) => p.categories?.slug === categorySlug) : products; const supabase = await createClient(); let query = supabase.from('products').select('*, categories!inner(name,slug)').eq('active', true).eq('categories.active', true).order('display_order'); if (categorySlug) query = query.eq('categories.slug', categorySlug); const { data } = await query; const items = (data ?? []) as Product[]; const [labels, variants] = await Promise.all([getPriceLabels(), getVariantsForProducts(items.map((item) => item.id))]); return addVariants(addPriceLabels(items, labels), variants); }
export async function getProduct(slug: string): Promise<Product | null> { if (!configured) return products.find((p) => p.slug === slug) ?? null; const supabase = await createClient(); const [{ data }, labels] = await Promise.all([supabase.from('products').select('*, categories!inner(name,slug)').eq('slug', slug).eq('active', true).single(), getPriceLabels()]); if (!data) return null; return addPriceLabels([data as Product], labels)[0]; }
export async function getVariants(productId:string):Promise<ProductVariant[]>{if(!configured)return [];const supabase=await createClient();const{data}=await supabase.from('product_variants').select('*').eq('product_id',productId).eq('active',true).order('is_default',{ascending:false}).order('display_order');return(data??[])as ProductVariant[]}
