'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { removeImage, uploadImage } from '@/lib/supabase/storage';
import { DEFAULT_WHATSAPP_NUMBER, normalizeWhatsAppNumber } from '@/lib/whatsapp';

type Values = Record<string, string>;
const defaults: Values = { forest: '#52604a', cream: '#f5f0e8', sand: '#e7dbca', clay: '#997245', text: '#39362f', textMuted: '#766d63', textOnDark: '#f6f0e7', brandText: '#f6f0e7', buttonText: '#ffffff', whatsappNumber: DEFAULT_WHATSAPP_NUMBER };

export default function Settings() {
  const supabase = useMemo(createClient, []);
  const [values, setValues] = useState<Values>(defaults);
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState('');
  useEffect(() => { supabase.from('site_settings').select('key,value').then(({ data }) => { const settings = Object.fromEntries((data ?? []).map((row) => [row.key, row.value])) as Record<string, Record<string, string>>; const contact = settings.contact ?? {}; setValues({ ...defaults, brandName: settings.brand?.name ?? '', tagline: settings.brand?.tagline ?? '', footer: settings.brand?.footer ?? '', heroTitle: settings.hero?.title ?? '', heroDescription: settings.hero?.description ?? '', heroButton: settings.hero?.buttonText ?? '', heroImage: settings.hero?.imageUrl ?? '', phone: contact.phone ?? '', whatsappNumber: normalizeWhatsAppNumber(contact.whatsappNumber), ...settings.theme }); }); }, [supabase]);
  const field = (key: string, label: string, type = 'text') => <label className="block text-sm font-semibold">{label}<input className="mt-1 w-full" type={type} value={values[key] ?? ''} onChange={(event) => setValues({ ...values, [key]: event.target.value })} /></label>;
  async function save(event: React.FormEvent) { event.preventDefault(); try { let heroImage = values.heroImage; if (file) { const next = await uploadImage(file, 'site'); await removeImage(heroImage); heroImage = next; } const whatsappNumber = normalizeWhatsAppNumber(values.whatsappNumber); const rows = [{ key: 'brand', value: { name: values.brandName, tagline: values.tagline, footer: values.footer } }, { key: 'hero', value: { title: values.heroTitle, description: values.heroDescription, buttonText: values.heroButton, imageUrl: heroImage } }, { key: 'contact', value: { phone: values.phone, whatsappNumber, whatsappUrl: `https://wa.me/${whatsappNumber}` } }, { key: 'theme', value: { forest: values.forest, cream: values.cream, sand: values.sand, clay: values.clay, text: values.text, textMuted: values.textMuted, textOnDark: values.textOnDark, brandText: values.brandText, buttonText: values.buttonText } }]; const { error } = await supabase.from('site_settings').upsert(rows); if (error) throw error; setValues({ ...values, heroImage, whatsappNumber }); setFile(null); setMessage('Configurações salvas.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao salvar.'); } }
  return <main className="mx-auto max-w-4xl p-6"><Link href="/admin" className="text-sm underline">← Voltar ao painel</Link><h1 className="mt-4 font-serif text-3xl">Configurações do catálogo</h1><form onSubmit={save} className="mt-6 space-y-5"><section className="rounded-lg bg-[#f2ece3] p-5"><h2 className="font-serif text-2xl">Marca e capa</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{field('brandName', 'Nome da marca')}{field('tagline', 'Slogan')}{field('footer', 'Texto do rodapé')}{field('heroTitle', 'Título da capa')}{field('heroDescription', 'Descrição')}{field('heroButton', 'Texto do botão')}{field('heroImage', 'URL da imagem atual')}<label className="block text-sm font-semibold">Enviar nova imagem da capa<input className="mt-1 w-full" type="file" accept="image/*" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>{values.heroImage && <img className="h-32 w-48 object-cover" src={values.heroImage} alt="Prévia" />}{field('phone', 'Telefone')}{field('whatsappNumber', 'Número do WhatsApp da loja')}</div></section><section className="rounded-lg bg-[#f2ece3] p-5"><h2 className="font-serif text-2xl">Cores</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{field('forest', 'Verde principal', 'color')}{field('cream', 'Fundo creme', 'color')}{field('sand', 'Faixa de diferenciais', 'color')}{field('clay', 'Fundo dos botões', 'color')}{field('buttonText', 'Texto dos botões', 'color')}{field('brandText', 'Texto do nome da marca', 'color')}{field('text', 'Texto principal', 'color')}{field('textMuted', 'Texto secundário', 'color')}{field('textOnDark', 'Texto em fundo escuro', 'color')}</div></section><button className="rounded bg-[#52604a] px-5 py-3 text-sm font-bold text-white">SALVAR CONFIGURAÇÕES</button>{message && <p>{message}</p>}</form></main>;
}
